test_data={'image_png_file': WindowsPath('testdata/files/image.png')}
http_client={'url': HttpUrl('http://localhost:8000/'), 'timeout': 100.0}
allure_results_dir=allure-results
swagger_coverage_services=[
    {
        "key": "api-course",
        "name": "API Course",
        "tags": ["API", "COURSES"],
        "repository": "https://github.com/janshv/stp_at_api",
        "swagger_url": "http://localhost:8000/openapi.json"
    }
]
swagger_coverage_html_report_file=./coverage.html
platform_info: Windows, 10
python_version:, 3.13.5 (tags/v3.13.5:6cb20a2, Jun 11 2025, 16:15:46) [MSC v.1943 64 bit (AMD64)]